 const actionTypes = {
     CALCULATE_PAYMENT_PLAN:"CALCULATE_PAYMENT_PLAN",
     SHOW_PAYMENT_PLAN:"SHOW_DETAILED_PAYMENT_PLAN",
     CHANGE_INTEREST:"CHANGE_INTEREST",
 };

 export default actionTypes;
